<?php
/**
 * Map data save and sanitisation tests.
 *
 * @package Waymark
 */

/**
 * Exercises the classic-editor save round trip through Waymark_Meta and
 * Waymark_Map, including the handling of escaped quotes in GeoJSON and the
 * sanitisation of overlay properties.
 */
class Test_Map_Data extends WP_UnitTestCase {

	/**
	 * Clean up request state after each test.
	 */
	public function tear_down() {
		$_POST = [];
		unset( $GLOBALS['post'] );

		parent::tear_down();
	}

	/**
	 * Simulate a classic-editor save the way a real request arrives: WordPress
	 * slashes the superglobals at request start (wp_magic_quotes) and
	 * Waymark_Meta::post_updated() then unslashes them before saving.
	 *
	 * @param int   $post_id     Map post ID.
	 * @param array $form_values Posted form values, unslashed.
	 */
	private function save_map_through_classic_editor( $post_id, array $form_values ) {
		$form_values['action']  = 'editpost';
		$form_values['post_ID'] = $post_id;

		// A real request includes the nonce generated by the meta box form.
		$form_values[ Waymark_Config::get_item( 'nonce_string' ) ] = wp_create_nonce( 'create_form' );

		$_POST = wp_slash( $form_values );

		// The admin save handler expects the post to be set up globally.
		$GLOBALS['post'] = get_post( $post_id );

		// post_updated passes ( $post_id, $post, $post_before ).
		do_action( 'post_updated', $post_id, get_post( $post_id ), get_post( $post_id ) );
	}

	/**
	 * Build a minimal GeoJSON FeatureCollection for a single marker.
	 *
	 * @param string $description Overlay description.
	 * @param string $title       Overlay title.
	 * @return array              GeoJSON FeatureCollection.
	 */
	private function feature_collection( $description = '', $title = '' ) {
		return [
			'type'     => 'FeatureCollection',
			'features' => [
				[
					'type'       => 'Feature',
					'geometry'   => [
						'type'        => 'Point',
						'coordinates' => [ -68.74923, 51.38436 ],
					],
					'properties' => [
						'title'       => $title,
						'description' => $description,
					],
				],
			],
		];
	}

	/**
	 * A classic-editor save round trips a link containing escaped quotes.
	 */
	public function test_classic_editor_save_round_trips_escaped_quotes_in_map_data() {
		$post_id = self::factory()->post->create(
			[
				'post_type'   => 'waymark_map',
				'post_status' => 'publish',
				'post_title'  => 'Round trip map',
			]
		);

		$description = '<a href="https://example.com">link</a>';
		$map_data    = wp_json_encode( $this->feature_collection( $description, 'Overlay' ) );

		// The encoded JSON must contain escaped quotes for this test to be meaningful.
		$this->assertStringContainsString( '\\"', $map_data, 'Test fixture should contain escaped quotes.' );

		$this->save_map_through_classic_editor( $post_id, [ 'map_data' => $map_data ] );

		$stored = get_post_meta( $post_id, 'waymark_map_data', true );

		$this->assertIsString( $stored );

		$decoded = json_decode( $stored, true );

		$this->assertIsArray( $decoded, 'Stored map data should be valid JSON: ' . json_last_error_msg() );
		$this->assertSame( 'FeatureCollection', $decoded['type'] );
		$this->assertSame( $description, $decoded['features'][0]['properties']['description'] );
		$this->assertSame( 'Overlay', $decoded['features'][0]['properties']['title'] );
		$this->assertStringContainsString( '\\"', $stored, 'Escaped quotes should survive the save.' );
	}

	/**
	 * Safe HTML is kept in overlay descriptions while scripts are stripped,
	 * and overlay titles are reduced to plain text.
	 */
	public function test_map_data_sanitisation_keeps_safe_html_and_strips_scripts() {
		$post_id = self::factory()->post->create(
			[
				'post_type'   => 'waymark_map',
				'post_status' => 'publish',
			]
		);

		$map_data = wp_json_encode(
			$this->feature_collection(
				'<a href="https://example.com">link</a><script>alert("xss")</script>',
				'<b>Overlay</b> Title'
			)
		);

		$this->save_map_through_classic_editor( $post_id, [ 'map_data' => $map_data ] );

		$decoded = json_decode( get_post_meta( $post_id, 'waymark_map_data', true ), true );

		$this->assertIsArray( $decoded, 'Stored map data should be valid JSON: ' . json_last_error_msg() );

		$properties = $decoded['features'][0]['properties'];

		$this->assertStringContainsString( '<a href="https://example.com">link</a>', $properties['description'] );
		$this->assertStringNotContainsString( '<script', $properties['description'] );
		$this->assertSame( 'Overlay Title', $properties['title'] );
	}
}
